### PR TITLE
fixed 100.0 sof bug plus refactor

### PR DESCRIPTION
**Pull request by pascal22p**

### CODE REVIEW

**Comment by richardicooper** [comment]
Thanks. An example of missing HKLF line is in the ins file in demo/sugar-disorder folder.

On Wed, 19 Feb 2020, 22:51 Pascal Parois, <notifications@github.com<mailto:notifications@github.com>> wrote:
________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/ChemCryst/crystals/pull/155

Commit Summary

  *   fixed 100.0 sof bug plus refactor

File Changes

  *   M bits/shelx2cry/build.sh<https://github.com/ChemCryst/crystals/pull/155/files#diff-0> (4)
  *   M bits/shelx2cry/crystal_data.F90<https://github.com/ChemCryst/crystals/pull/155/files#diff-1> (2)
  *   M bits/shelx2cry/shelx2cry_mod.F90<https://github.com/ChemCryst/crystals/pull/155/files#diff-2> (178)

Patch Links:

  *   https://github.com/ChemCryst/crystals/pull/155.patch
  *   https://github.com/ChemCryst/crystals/pull/155.diff

**Comment by pascal22p** [comment]
> demo/sugar-disorder

It is what I get after the fix within the PR

[crystalsinput.cry.txt](https://github.com/ChemCryst/crystals/files/4229983/crystalsinput.cry.txt)

**Comment by pascal22p** [comment]
If this is OK, I will update the tests then merge in master. After that I can pull the changes into the other branch https://github.com/ChemCryst/crystals/tree/shelx2cry_fix_for_when_no_hklf_card_in_ins

**Comment by richardicooper** [comment]
The file you sent has a null matrix in the HKLI instruction. This makes all
the indices zero when you import into crystals. They then all get merged
into one reflection. Causes bad confusion!

**Comment by richardicooper** [comment]
Oh, I see - let's merge this one, then update the other branch for the missing HKLF instruction case.

**Pull request merged**
